### PR TITLE
Blog post about parallel containers with Jenkins

### PR DESCRIPTION
**Pull request by ljpengelen**

### CODE REVIEW

**Comment by pascalw** [comment]
Nicely written.

At Kabisa we usually run all dependencies like the database in a single container. This makes the Jenkinsfile a bit simpler, at the expense of the Dockerfile becoming a bit more complex.

It's a shame that this pattern is not as well supported in Jenkins, as it is in GitLab CI for example.

**Comment by obeleh** [comment]
@pascalw running multiple processes in a single container is an anti-pattern. Containers are about isolation. You _can_ package things together and manage you processes with tools like supervisor. But I believe packaging multiple processes in the same container should be shunned. Can you give more examples where it would be advised to do it anyway? @ljpengelen I have no experience with Jenkins but would it be possible to run a docker-compose environment? The advantage would be that it would be descriptive in stead of imperative?

**Comment by ljpengelen** [comment]
@obeleh, after I published this post, David Vollmar let me know that he wrote this: https://github.com/kabisa/continuous-integration/blob/master/bin/run-composed. His tl;dr was that this is docker-compose instead of docker for your CI.

There's also a Jenkins plugin for Docker compose: https://wiki.jenkins.io/display/JENKINS/Docker+Compose+Build+Step+Plugin

**Comment by pascalw** [comment]
@obeleh I agree, but in the context of Jenkins it's the most practical solution. Unfortunately Jenkins pipelines don't support 'sidecar' containers on plain Docker. It is supported via [Kubernetes](https://github.com/jenkinsci/kubernetes-plugin#declarative-pipeline).

The downside of using the `run-composed` script or that Docker compose plugin is that it's not integrated with Jenkins pipelines.

**Pull request merged**
